spring:
      application:
            name: auth-ms-colegio
      r2dbc:
            url: r2dbc:mysql://mysql-container:3390/auth
            username: root-auth
            password: 12345
      kafka:
            producer:
                  bootstrap-servers: kafka:9092
server:
      port: 8080

security:
      password:
            # Lee la variable de entorno DEFAULT_PASSWORD. Si no existe, usa 12345 como valor por defecto.
            default: ${DEFAULT_PASSWORD:12345}
      jwt:
            # Lee la variable de entorno JWT_SECRET.
            secret: ${JWT_SECRET}
            issuer: Main
            ttlMillis: 3600000
            ttMillisExpired: 86400000
