spring:
    application:
        name: auth-ms-colegio
    r2dbc:
        url: r2dbc:mysql://localhost:3390/auth
        username: root-auth
        password: 12345
server:
    port: 8080

security:
    password:
        default: 10002000
    jwt:
        secret: 9s12weewwfefefn9j1264599s12weewwfefefn9j12645s12weewwfefefn9j12645
        issuer: Main
        ttlMillis: 3600000
        ttMillisExpired: 86400000
        # 1 second = 1000 milliseconds, 1 minute = 60000 milliseconds, 1 hour = 3600000 milliseconds